"""create card_likes table

Revision ID: a44f83ab724b
Revises: 9d83480bdb19
Create Date: 2026-09-18 08:30:37.523034

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a44f83ab724b'
down_revision: str | Sequence[str] | None = '9d83480bdb19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_likes',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('card_num', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('date', 'card_num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_likes')
    # ### end Alembic commands ###
